### ISSUE TITLE
Panic with depths greater than 31

### ISSUE THREAD

**Issue by michidk** [ambuc/quadtree#5]
Starting with depth values equal to or larger than 31, the following panic occurs:
```
thread 'main' panicked at 'attempt to multiply with overflow', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\num\mod.rs:210:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\panicking.rs:143
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\panicking.rs:48
   3: core::num::impl$2::pow
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\num\int_macros.rs:1927
   4: num_traits::int::impl$8::pow
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\num-traits-0.2.15\src\int.rs:492
   5: quadtree_rs::qtinner::QTInner<i32>::new<i32>
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\quadtree_rs-0.1.2\src\qtinner.rs:76
   6: quadtree_rs::Quadtree<i32,enum$<citypol_server::map::Building, House> >::new_with_anchor<i32,enum$<citypol_server::map::Building, House> >
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\quadtree_rs-0.1.2\src\lib.rs:247
   7: quadtree_rs::Quadtree<i32,enum$<citypol_server::map::Building, House> >::new<i32,enum$<citypol_server::map::Building, House> >
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\quadtree_rs-0.1.2\src\lib.rs:217
   8: citypol_server::map::Map::new
             at .\src\map.rs:45
   9: citypol_server::GameState::new
             at .\src\main.rs:55
  10: citypol_server::main::async_block$0
             at .\src\main.rs:117
  11: core::future::from_generator::impl$1::poll<citypol_server::main::async_block_env$0>
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\future\mod.rs:84
  12: tokio::park::thread::impl$5::block_on::closure$0<core::future::from_generator::GenFuture<citypol_server::main::async_block_env$0> >
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\park\thread.rs:263
  13: tokio::coop::with_budget::closure$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::future::from_generator::GenFuture<citypol_server::main::async_block_env$0> > >
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\coop.rs:102
  14: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<cor
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\std\src\thread\local.rs:413
  15: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::f
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\std\src\thread\local.rs:389
  16: tokio::coop::with_budget
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\coop.rs:95
  17: tokio::coop::budget
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\coop.rs:72
  18: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<citypol_server::main::async_block_env$0> >
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\park\thread.rs:263
  19: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<citypol_server::main::async_block_env$0> >
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\enter.rs:151
  20: tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<citypol_server::main::async_block_env$0> >
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\thread_pool\mod.rs:81
  21: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<citypol_server::main::async_block_env$0> >
             at C:\Users\michi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\mod.rs:477
  22: citypol_server::main
             at .\src\main.rs:123
  23: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\citypol-server.exe` (exit code: 101)
```

**Comment by ambuc** [comment]
Sorry that you encountered this bug, @michidk. I do not have bandwidth to investigate and fix this at the moment, but if the issue affects you/your project and you feel like digging into it, your contributions would be most welcome :)
